name: Deploy API to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/cli.sh | bash

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.RAILWAY_SERVICE }} --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run Laravel Migrations
        run: railway run --service=${{ secrets.RAILWAY_SERVICE }} "php artisan migrate --force"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
