name: Deploy API to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.RAILWAY_SERVICE }} --yes

      - name: Run Laravel Migrations
        run: railway run php artisan migrate --force --service=${{ secrets.RAILWAY_SERVICE }}
